/**
 * Finishes the build: writes dist/_headers and rewrites the web manifest.
 *
 * The Content-Security-Policy has to name the Supabase project, and that is
 * only known from the environment — hardcoding it in a checked-in file would
 * silently break the site the day the project changes.
 */
import { writeFileSync, readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function supabaseOrigin() {
  const fromEnv = process.env.VITE_SUPABASE_URL;
  if (fromEnv) return new URL(fromEnv).origin;
  // Local builds read .env, which Vite has already applied to its own bundle.
  try {
    const env = readFileSync(resolve(root, '.env'), 'utf8');
    const m = env.match(/^VITE_SUPABASE_URL=(.+)$/m);
    if (m) return new URL(m[1].trim()).origin;
  } catch {}
  throw new Error('VITE_SUPABASE_URL is not set — cannot write a correct CSP');
}

function shopFromEnvFile() {
  try {
    const env = readFileSync(resolve(root, '.env'), 'utf8');
    const m = env.match(/^VITE_SHOP_NAME=(.+)$/m);
    return m ? m[1].trim() : null;
  } catch { return null; }
}

const api = supabaseOrigin();
const ws = api.replace(/^https:/, 'wss:'); // realtime uses a websocket

const csp = [
  "default-src 'self'",
  `connect-src 'self' ${api} ${ws}`,
  "img-src 'self' data:",
  // Tailwind injects a style element, so inline styles have to be allowed.
  "style-src 'self' 'unsafe-inline'",
  "script-src 'self'",
  "font-src 'self'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
].join('; ');

const headers = `# Generated by scripts/headers.mjs — do not edit by hand.
/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Content-Security-Policy: ${csp}

# Hashed filenames never change contents, so they can be cached hard.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# The entry point must not be, or a deploy would not reach anyone.
/index.html
  Cache-Control: public, max-age=0, must-revalidate
`;

writeFileSync(resolve(root, 'dist/_headers'), headers);
console.log('[postbuild] _headers written, api origin =', api);

// The manifest carries the shop's name onto the phone home screen, so it has
// to be built rather than shipped fixed — same reason as the CSP above.
const shop = (process.env.VITE_SHOP_NAME || shopFromEnvFile() || 'PharmaFlow').trim();
const manifestPath = resolve(root, 'dist/manifest.webmanifest');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
manifest.name = shop;
manifest.short_name = shop.length > 12 ? shop.split(/\s+/)[0] : shop;
writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
console.log('[postbuild] manifest name =', shop);
